#!/usr/bin/env python
# -*- coding:utf-8 -*- 
#Author: qiantu
#qq 261767353

import xml.etree.cElementTree as ET
job_list=["pay","member","weapon","trade","wealth","statistics","bops","napp","site","crm","channel","tiger","rams","activity","api","eagle","squirrel","wap","dragon","tengu"]
tree = ET.ElementTree(file="jenkins_job.xml")

# root = tree.getroot()
# print root[0][1].attrib
# for ele in tree.iter():
#     print ele.tag, ele.attrib

def create_job_file(name):
    for ele in tree.iterfind("properties/hudson.model.ParametersDefinitionProperty/parameterDefinitions/hudson.model.StringParameterDefinition/defaultValue"):
        ele.text="mycms"
        ele.set("updated","up")
    tree.write("jenkins_job_"+name+".xml")

for i in job_list:
    create_job_file(i)

